on: issue_comment

jobs:
  check-pr-command:
    runs-on: ubuntu-latest
    outputs:
      triggered: ${{ steps.check.outputs.triggered }}
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'build commerce pr'

  pr_commented:
    if: needs.check-pr-command.outputs.triggered == 'true'
    # This job only runs for pull request comments
    name: PR comment
    runs-on: ubuntu-latest
    needs: check-pr-command
    steps:
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"

